# Generated by Django 3.2.8 on 2024-01-26 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('failed', 'failed'), ('finished', 'finished')], db_index=True, default='created', max_length=10)),
                ('music_url', models.URLField(db_index=True, max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('download_video_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('retrieved_from_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiktokaggregator.musicpost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
