# Generated by Django 3.2.8 on 2024-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokaggregator', '0002_musicpost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='download_video_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
