# Generated by Django 3.2.8 on 2024-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokaggregator', '0003_auto_20240126_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='video',
        ),
        migrations.AddField(
            model_name='musicpost',
            name='video_archive',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
