# Generated by Django 3.2.8 on 2024-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokaggregator', '0004_auto_20240126_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('uploadedToS3', 'uploadedToS3')], db_index=True, default='created', max_length=15),
        ),
    ]
