# Generated by Django 3.2.8 on 2024-01-26 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokaggregator', '0005_videopost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(db_index=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='profile',
        ),
        migrations.AddField(
            model_name='musicpost',
            name='profile_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tiktokaggregator.profile'),
        ),
    ]
