# Generated by Django 3.2.8 on 2024-01-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokaggregator', '0006_auto_20240126_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicpost',
            name='video_archive',
        ),
        migrations.AddField(
            model_name='profile',
            name='video_archive',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
